version: '3'

services:
  db:
    image: mysql
    container_name: backend_db
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    # healthcheck:
    #   # test: ["CMD", "mysql", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "SELECT 1"]
    #   test:
    #     - CMD-SHELL
    #     - mysqladmin ping -h localhost --password=mypassword
        
    #   # timeout: 20s  # Increase the timeout if necessary
    #   interval: 1s
    #   retries: 10

  redis:
    image: redis:alpine
    container_name: backend_redis

  django:
    build: .
    container_name: backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure:10
    ports:
      - '8000:8000'
    # env_file:
    #   - .env
    depends_on:
      - db
        # condition: service_healthy
        # # restart: true
        # required: true
      - redis
        # condition: service_started
    mem_limit: 1g


