# Generated by Django 5.0 on 2023-12-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="todoitem",
            name="tags",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="api.tag"),
        ),
    ]
