# Generated by Django 5.0 on 2023-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_tag_remove_todoitem_tags_todoitem_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="tags",
            field=models.ManyToManyField(blank=True, to="api.tag"),
        ),
    ]
